version: "3.7"

services:    
    # docker exec openldap ldapsearch -x -H ldap://localhost -b dc=example,dc=org -D "cn=admin,dc=example,dc=org" -w admin

    ldap-service:
        image: osixia/openldap:1.3.0
        container_name: ldap-service
        hostname: ldap-service
        environment: 
            LDAP_ADMIN_PASSWORD: "admin"
            LDAP_CONFIG_PASSWORD: "config"
            LDAP_READONLY_USER_USERNAME: "readonly"
            LDAP_READONLY_USER_PASSWORD: "readonly"
            LDAP_DOMAIN: "example.org"
            LDAP_BASE_DN: "dc=example,dc=org"
        ports:
            - "8090:90"

    # docker run --name phpldapadmin-service 
    # --hostname phpldapadmin-service 
    # --link ldap-service:ldap-service 
    # --env PHPLDAPADMIN_LDAP_HOSTS=ldap-service 
    ldap-gui:
        image: osixia/phpldapadmin:0.9.0
        container_name: phpldapadmin-service
        hostname: phpldapadmin-service
        environment:
            - PHPLDAPADMIN_LDAP_HOSTS=ldap-service
            - PHPLDAPADMIN_HTTPS=false
        ports:
            - "8080:80"
        depends_on:
            - ldap-service